INSERT INTO `brands` (`brand_id`, `title`, `category_id`) VALUES (1, 'apple', 1);
INSERT INTO `brands` (`brand_id`, `title`, `category_id`) VALUES (2, 'sumsung', 1);
INSERT INTO `brands` (`brand_id`, `title`, `category_id`) VALUES (3, 'huawi', 1);
INSERT INTO `brands` (`brand_id`, `title`, `category_id`) VALUES (4, 'benz', 2);
INSERT INTO `brands` (`brand_id`, `title`, `category_id`) VALUES (5, 'nike', 3);
INSERT INTO `categories` (`category_id`, `title`, `parent_id`) VALUES (1, 'elec', 0);
INSERT INTO `categories` (`category_id`, `title`, `parent_id`) VALUES (2, 'cars', 0);
INSERT INTO `categories` (`category_id`, `title`, `parent_id`) VALUES (3, 'sports', 0);
INSERT INTO `product_atr` (`product_atr_id`, `key`, `value`, `product_meta_ref_id`) VALUES (1, 'color', 'blue', 1);
INSERT INTO `product_atr` (`product_atr_id`, `key`, `value`, `product_meta_ref_id`) VALUES (2, 'size led', '32', 1);
INSERT INTO `product_atr` (`product_atr_id`, `key`, `value`, `product_meta_ref_id`) VALUES (3, 'ram', '128', 1);
INSERT INTO `product_atr` (`product_atr_id`, `key`, `value`, `product_meta_ref_id`) VALUES (4, 'battry', 'litum', 1);
INSERT INTO `product_meta` (`product_meta_id`, `brand_ref_id`, `price`, `description`, `quantity`, `products_ref_id`) VALUES (1, 1, 80000, 'nmnm,nmn', 3, 1);
INSERT INTO `product_meta` (`product_meta_id`, `brand_ref_id`, `price`, `description`, `quantity`, `products_ref_id`) VALUES (2, 1, 90000, 'sdfdfsdfd', 1, 3);
INSERT INTO `product_meta` (`product_meta_id`, `brand_ref_id`, `price`, `description`, `quantity`, `products_ref_id`) VALUES (3, 4, 300000, 'sdfdsfs', 12, 2);
INSERT INTO `product_meta` (`product_meta_id`, `brand_ref_id`, `price`, `description`, `quantity`, `products_ref_id`) VALUES (4, 1, 20000, 'nbnn', 3, 4);
INSERT INTO `products` (`product_id`, `name`) VALUES (1, '7');
INSERT INTO `products` (`product_id`, `name`) VALUES (2, 'c500');
INSERT INTO `products` (`product_id`, `name`) VALUES (3, '8');
INSERT INTO `products` (`product_id`, `name`) VALUES (4, '6');
INSERT INTO `sub_category` (`sub_category_id`, `category_ref_id`, `title`, `description`, `barand_id`) VALUES (1, 1, 'mobile', 'mobile phone', NULL);
INSERT INTO `sub_category` (`sub_category_id`, `category_ref_id`, `title`, `description`, `barand_id`) VALUES (2, 1, 'watch', 'mobile watch', NULL);
INSERT INTO `sub_category` (`sub_category_id`, `category_ref_id`, `title`, `description`, `barand_id`) VALUES (3, 1, 'tv', 'televesion ', 0);
INSERT INTO `sub_category` (`sub_category_id`, `category_ref_id`, `title`, `description`, `barand_id`) VALUES (4, 1, 'game console', 'mae console', NULL);
INSERT INTO `sub_category` (`sub_category_id`, `category_ref_id`, `title`, `description`, `barand_id`) VALUES (5, 1, 'labtab', 'port able camputer', NULL);
INSERT INTO `sub_category` (`sub_category_id`, `category_ref_id`, `title`, `description`, `barand_id`) VALUES (6, 2, 'offroad', 'cars off road', NULL);
INSERT INTO `sub_category` (`sub_category_id`, `category_ref_id`, `title`, `description`, `barand_id`) VALUES (7, 3, 'ball', 'football ball ', NULL);
